# Generated by Django 3.2.9 on 2023-03-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('github_link', models.CharField(blank=True, default='', max_length=200)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('profile_image', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_type', models.CharField(choices=[('EDU', 'Education'), ('WORK', 'Work Experience')], default='WORK', max_length=10)),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('responsibility', models.TextField(blank=True, default='')),
                ('projects', models.TextField(blank=True, default='')),
                ('technologies', models.TextField(blank=True, default='')),
                ('reference', models.TextField(blank=True, default='')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('github_link', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.CharField(blank=True, default='', max_length=200)),
                ('thumbnail', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(blank=True, default='', max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.genre')),
            ],
        ),
    ]
